// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type NewSchedule struct {
	Summary string    `json:"summary"`
	Start   time.Time `json:"start"`
	End     time.Time `json:"end"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Schedule struct {
	ID      string    `json:"id"`
	Summary string    `json:"summary"`
	Start   time.Time `json:"start"`
	End     time.Time `json:"end"`
}

type ScheduleID struct {
	ID string `json:"id"`
}

type ScheduleTime struct {
	ID    string    `json:"id"`
	Start time.Time `json:"start"`
	End   time.Time `json:"end"`
}

type ScheduleTitle struct {
	ID      string `json:"id"`
	Summary string `json:"summary"`
}

type Todo struct {
	ID     string `json:"id"`
	Text   string `json:"text"`
	Done   bool   `json:"done"`
	UserID string `json:"userId"`
	User   *User  `json:"user"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
